"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("index");
var drawBankDetails = function (doc, y, data) {
    var posY = y;
    var posX = index_1.margins.left + 12;
    doc.setFont("KanitLight", "normal");
    doc.text("Account owner", posX, posY);
    doc.text(data.inhaber, posX + index_1.margins.quarter, posY);
    posY += 5;
    doc.text("IBAN", posX, posY);
    doc.text(data.IBAN, posX + index_1.margins.quarter, posY);
    posY += 5;
    doc.text("BIC", posX, posY);
    doc.text(data.BIC, posX + index_1.margins.quarter, posY);
    posY += 5;
    doc.text("Bank", posX, posY);
    doc.text(data.bank, posX + index_1.margins.quarter, posY);
    posY += 5;
    return posY;
};
exports.default = drawBankDetails;
